repos:
- repo: local
  hooks:
  - id: ruff check
    name: ruff check
    language: system
    files: \.py$
    entry: ruff check --fix
  - id: ruff format
    name: ruff format
    language: system
    files: \.py$
    entry: ruff format
